import type { ComponentType, SVGProps } from "react";
import { SiWhatsapp } from "@icons-pack/react-simple-icons";
import {
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  BarChart3,
  BellRing,
  Box,
  Building2,
  Bus,
  Check,
  CheckCircle,
  CheckCheck,
  CircleX,
  Clock3,
  FilePlus2,
  GalleryHorizontal,
  Layers,
  Lightbulb,
  Map,
  MapPin,
  Menu,
  MessageCircle,
  Palette,
  PenSquare,
  Phone,
  Play,
  Printer,
  Route,
  Scissors,
  Settings2,
  Store,
  Star,
  Text,
  X,
  Wrench,
} from "lucide-react";

const icons: Record<string, ComponentType<SVGProps<SVGSVGElement>>> = {
  "solar:arrow-left-linear": ArrowLeft,
  "solar:arrow-right-linear": ArrowRight,
  "solar:arrow-right-up-linear": ArrowUpRight,
  "solar:play-linear": Play,
  "solar:phone-linear": Phone,
  "solar:phone-calling-linear": Phone,
  "solar:hamburger-menu-linear": Menu,
  "solar:close-circle-linear": CircleX,
  "solar:check-read-linear": CheckCheck,
  "solar:check-circle-linear": CheckCircle,
  "solar:check-circle-bold": CheckCircle,
  "solar:pallete-2-linear": Palette,
  "solar:widget-linear": Box,
  "solar:verified-check-linear": CheckCircle,
  "solar:document-add-linear": FilePlus2,
  "solar:pen-new-square-linear": PenSquare,
  "solar:box-linear": Box,
  "solar:star-bold": Star,
  "solar:letter-linear": MessageCircle,
  "solar:map-point-linear": MapPin,
  "solar:clock-circle-linear": Clock3,
  "solar:settings-minimalistic-linear": Settings2,
  "solar:routing-2-linear": Route,
  "solar:shop-linear": Store,
  "solar:text-bold-linear": Text,
  "solar:lightbulb-linear": Lightbulb,
  "solar:layers-linear": Layers,
  "solar:map-linear": Map,
  "solar:medal-star-linear": Star,
  "solar:bus-linear": Bus,
  "solar:printer-linear": Printer,
  "solar:scissors-linear": Scissors,
  "solar:gallery-wide-linear": GalleryHorizontal,
  "solar:widget-4-linear": Wrench,
  "solar:tuning-2-linear": Settings2,
  "solar:buildings-linear": Building2,
  "simple-icons:whatsapp": SiWhatsapp,
  "simple-icons:x": X,
  "solar:chart-linear": BarChart3,
  "solar:bell-linear": BellRing,
  "solar:check-linear": Check,
};

type IconProps = SVGProps<SVGSVGElement> & {
  icon: string;
};

export function Icon({ icon, ...props }: IconProps) {
  const Component = icons[icon] ?? CircleX;
  return <Component {...props} aria-hidden={props["aria-label"] ? undefined : true} />;
}
